import React, { useState } from 'react';
import { SchemaMapping } from '../../types';

interface GenerateSqlModalProps {
  isOpen: boolean;
  onClose: () => void;
  mappings: SchemaMapping[];
  tableName?: string;
}

export const GenerateSqlModal: React.FC<GenerateSqlModalProps> = ({
  isOpen,
  onClose,
  mappings,
  tableName = 'shopify_orders_stream'
}) => {
  const [dialect, setDialect] = useState<'postgresql' | 'sqlite' | 'bigquery'>('postgresql');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const typeMapPostgres: Record<string, string> = {
    'Integer': 'BIGINT',
    'String': 'VARCHAR(255)',
    'Decimal/Currency': 'NUMERIC(12, 2)',
    'ISO-8601': 'TIMESTAMPTZ',
    'Computed': 'NUMERIC(12, 2)',
    'Enum': 'VARCHAR(32)',
    'Boolean': 'BOOLEAN'
  };

  const typeMapSqlite: Record<string, string> = {
    'Integer': 'INTEGER',
    'String': 'TEXT',
    'Decimal/Currency': 'REAL',
    'ISO-8601': 'TEXT',
    'Computed': 'REAL',
    'Enum': 'TEXT',
    'Boolean': 'INTEGER'
  };

  const typeMapBigQuery: Record<string, string> = {
    'Integer': 'INT64',
    'String': 'STRING',
    'Decimal/Currency': 'NUMERIC',
    'ISO-8601': 'TIMESTAMP',
    'Computed': 'FLOAT64',
    'Enum': 'STRING',
    'Boolean': 'BOOL'
  };

  const generateDDL = () => {
    if (dialect === 'sqlite') {
      const cols = mappings.map(m => {
        const sqlType = typeMapSqlite[m.targetType] || 'TEXT';
        const isPk = m.outputField.toLowerCase().includes('id') && m.targetType === 'Integer' ? ' PRIMARY KEY' : '';
        return `  ${m.outputField} ${sqlType}${isPk}`;
      }).join(',\n');

      return `-- SQLite Ingestion Table DDL
-- Generated by API Data Bridge v2.4

CREATE TABLE IF NOT EXISTS ${tableName} (
${cols},
  _ingested_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_${tableName}_order_id ON ${tableName}(${mappings[0]?.outputField || 'order_id'});`;
    }

    if (dialect === 'bigquery') {
      const cols = mappings.map(m => {
        const bqType = typeMapBigQuery[m.targetType] || 'STRING';
        return `  ${m.outputField} ${bqType}`;
      }).join(',\n');

      return `-- Google Cloud BigQuery Table DDL
-- Generated by API Data Bridge v2.4

CREATE OR REPLACE TABLE \`enterprise_data_lake.ingestion_${tableName}\` (
${cols},
  _ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(_ingestion_timestamp)
CLUSTER BY ${mappings[0]?.outputField || 'order_id'};`;
    }

    // PostgreSQL Default
    const cols = mappings.map((m, i) => {
      const pgType = typeMapPostgres[m.targetType] || 'TEXT';
      const isPk = i === 0 ? ' PRIMARY KEY' : '';
      return `  ${m.outputField} ${pgType}${isPk}`;
    }).join(',\n');

    return `-- PostgreSQL ANSI DDL Schema Definition
-- Generated by API Data Bridge v2.4 Schema Transformer

CREATE TABLE IF NOT EXISTS ${tableName} (
${cols},
  _ingested_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  _checksum VARCHAR(64)
);

CREATE INDEX IF NOT EXISTS idx_${tableName}_created_at ON ${tableName}(created_at_utc);
COMMENT ON TABLE ${tableName} IS 'Auto-generated ingestion sink from Shopify Admin API';`;
  };

  const ddlScript = generateDDL();

  const handleCopy = () => {
    navigator.clipboard.writeText(ddlScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const dataStr = "data:text/plain;charset=utf-8," + encodeURIComponent(ddlScript);
    const dl = document.createElement('a');
    dl.setAttribute("href", dataStr);
    dl.setAttribute("download", `${tableName}-${dialect}.sql`);
    document.body.appendChild(dl);
    dl.click();
    dl.remove();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm overflow-y-auto">
      <div className="bg-[#181c24] border border-[#31353e] rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col my-8 animate-in fade-in zoom-in-95">
        <div className="p-4 border-b border-[#262a33] bg-[#141820] flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-lg bg-[#262a33] border border-[#31353e] text-[#7bd0ff]">
              <span className="material-symbols-outlined text-[20px]">database</span>
            </div>
            <div>
              <h2 className="text-sm font-bold text-white tracking-tight font-sans">
                Generate Database DDL Schema
              </h2>
              <p className="text-[11px] text-[#908fa0] font-mono">
                Transformed schema from 18 active mapped ingestion columns
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-[#908fa0] hover:text-white rounded"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>

        {/* Dialect Selector */}
        <div className="p-4 bg-[#0a0e16] border-b border-[#262a33] flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <span className="text-xs text-[#908fa0] font-mono">SQL Dialect:</span>
            <div className="flex items-center bg-[#181c24] border border-[#262a33] rounded-lg p-0.5 text-xs font-mono">
              {(['postgresql', 'sqlite', 'bigquery'] as const).map(d => (
                <button
                  key={d}
                  onClick={() => setDialect(d)}
                  className={`px-3 py-1 rounded capitalize transition-all ${
                    dialect === d ? 'bg-[#262a33] text-[#c0c1ff] font-bold' : 'text-[#908fa0] hover:text-white'
                  }`}
                >
                  {d}
                </button>
              ))}
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="px-3 py-1 bg-[#181c24] hover:bg-[#262a33] text-[#7bd0ff] rounded text-xs font-mono border border-[#262a33] flex items-center space-x-1"
            >
              <span className="material-symbols-outlined text-[14px]">
                {copied ? 'check' : 'content_copy'}
              </span>
              <span>{copied ? 'Copied!' : 'Copy Script'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-3 py-1 bg-[#8083ff] hover:bg-[#9194ff] text-[#0d0096] rounded text-xs font-mono font-bold flex items-center space-x-1"
            >
              <span className="material-symbols-outlined text-[14px]">download</span>
              <span>Download .sql</span>
            </button>
          </div>
        </div>

        {/* DDL Code Area */}
        <div className="p-4 bg-[#05070a] overflow-auto max-h-96">
          <pre className="font-mono text-xs text-[#4edea3] leading-relaxed select-all whitespace-pre">
            {ddlScript}
          </pre>
        </div>

        {/* Footer */}
        <div className="p-3 bg-[#141820] border-t border-[#262a33] flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-1.5 bg-[#262a33] hover:bg-[#31353e] text-white rounded-lg text-xs font-medium"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
